"use client";

type CategoryProduct = {
    name: string;
    price: string;
    oldPrice: string;
    brand: string;
    seller: string;
    rating: string;
    reviews: string;
    shipping: string;
    discount: string;
    accent: string;
    art: string;
    image?: string;
    kind?: string;
    id: string;
};

export const categoryProducts: Record<string, CategoryProduct[]> = {
    "For You": [
        {
            name: "Premium Picks",
            price: "₹1,499.00",
            oldPrice: "₹1,799",
            brand: "Curated for you",
            seller: "Fixx Select",
            rating: "4.8",
            reviews: "(128)",
            shipping: "Free",
            discount: "12% OFF",
            accent: "from-[#f5efe4] to-[#ead8c4]",
            art: "SP",
            id: ""
        },
        {
            name: "Daily Essentials",
            price: "₹249.00",
            oldPrice: "₹299",
            brand: "Top rated",
            seller: "Fixx Select",
            rating: "4.6",
            reviews: "(84)",
            shipping: "Free",
            discount: "15% OFF",
            accent: "from-[#e8f0ff] to-[#d4e1ff]",
            art: "BG",
            id: ""
        },
    ],
    Accessories: [
        {
            kind: "accessory",
            name: "Round Diamond Pendant Necklace",
            price: "₹1,170.00",
            oldPrice: "₹1,340",
            brand: "THE FUTURE ROCKS",
            seller: "THE FUTURE ROCKS",
            rating: "4.9",
            reviews: "(411)",
            shipping: "Free",
            discount: "13% OFF",
            accent: "from-[#fffaf0] to-[#f5e4b8]",
            art: "D1",
            image: "/watch-images/shopping.webp",
            id: ""
        },
        {
            kind: "accessory",
            name: "14kt Gold Open Heart Pendant",
            price: "₹1,294.00",
            oldPrice: "₹1,440",
            brand: "Ritani",
            seller: "Ritani",
            rating: "4.8",
            reviews: "(220)",
            shipping: "Free",
            discount: "10% OFF",
            accent: "from-[#fff8ef] to-[#f0d6a0]",
            art: "H1",
            id: ""
        },
        {
            kind: "accessory",
            name: "Round Diamond Pendant Necklace",
            price: "₹1,170.00",
            oldPrice: "₹1,340",
            brand: "THE FUTURE ROCKS",
            seller: "THE FUTURE ROCKS",
            rating: "4.7",
            reviews: "(97)",
            shipping: "Free",
            discount: "13% OFF",
            accent: "from-[#f8fbff] to-[#dfe8f7]",
            art: "D2",
            id: ""
        },
        {
            kind: "accessory",
            name: "Pacific Green Lab Diamond Pave",
            price: "₹2,195.00",
            oldPrice: "₹2,560",
            brand: "Brilliant Earth",
            seller: "Brilliant Earth",
            rating: "4.9",
            reviews: "(63)",
            shipping: "Free",
            discount: "14% OFF",
            accent: "from-[#f8fff7] to-[#d8f0da]",
            art: "G1",
            id: ""
        },
        {
            kind: "accessory",
            name: "BVLGARI Serpenti Bracelet",
            price: "₹26,000.00",
            oldPrice: "₹29,000",
            brand: "BVLGARI",
            seller: "BVLGARI",
            rating: "4.6",
            reviews: "(18)",
            shipping: "Free",
            discount: "10% OFF",
            accent: "from-[#fff4ef] to-[#f4d1b6]",
            art: "S1",
            id: ""
        },
        {
            kind: "accessory",
            name: "Libra Zodiac Diamond Medallion Necklace",
            price: "₹1,295.00",
            oldPrice: "₹1,480",
            brand: "Brilliant Earth",
            seller: "Brilliant Earth",
            rating: "4.7",
            reviews: "(104)",
            shipping: "Free",
            discount: "12% OFF",
            accent: "from-[#fffbe8] to-[#f1e0a2]",
            art: "LB",
            id: ""
        },
        {
            kind: "accessory",
            name: "67 Pave Diamond Numerology Necklace",
            price: "₹27,850.00",
            oldPrice: "₹31,000",
            brand: "Logan Hollowell",
            seller: "Logan Hollowell",
            rating: "4.8",
            reviews: "(22)",
            shipping: "Free",
            discount: "10% OFF",
            accent: "from-[#faf7ff] to-[#e7def9]",
            art: "67",
            id: ""
        },
        {
            kind: "accessory",
            name: "Ballerina Blue Diamond Earrings",
            price: "₹590.00",
            oldPrice: "₹690",
            brand: "THE FUTURE ROCKS",
            seller: "THE FUTURE ROCKS",
            rating: "4.9",
            reviews: "(41)",
            shipping: "Free",
            discount: "15% OFF",
            accent: "from-[#f2fbff] to-[#d7eefc]",
            art: "B1",
            id: ""
        },
    ],
    Watches: [
        {
            kind: "watch",
            name: "Sylvi Men's Imperial Analog Watch",
            price: "₹97.50",
            oldPrice: "₹195",
            brand: "Sylvi & more",
            seller: "Sylvi & more",
            rating: "4.2",
            reviews: "(14)",
            shipping: "Free delivery",
            discount: "LOW PRICE",
            accent: "from-[#f5f5f3] to-[#e5e4e0]",
            art: "F1",
            image: "/watch-images/fossil-mens-privater.svg",
            id: ""
        },
        {
            kind: "watch",
            name: "Sonata Verve Quartz Analog Watch",
            price: "₹194.65",
            oldPrice: "₹229",
            brand: "Amazon.in",
            seller: "Amazon.in",
            rating: "4.9",
            reviews: "(411)",
            shipping: "Free delivery",
            discount: "LOW PRICE",
            accent: "from-[#f6efe6] to-[#ead7be]",
            art: "RC",
            image: "/watch-images/ralph-christian-intrepid.svg",
            id: ""
        },
        {
            kind: "watch",
            name: "Timex Men's Round Dial Analog Watch",
            price: "₹429.00",
            oldPrice: "₹529",
            brand: "Amazon.in & more",
            seller: "Amazon.in & more",
            rating: "4.8",
            reviews: "(10K)",
            shipping: "Free delivery",
            discount: "LOW PRICE",
            accent: "from-[#f3f4ef] to-[#dfe4d9]",
            art: "AW",
            image: "/watch-images/apple-watch-series-11.svg",
            id: ""
        },
        {
            kind: "watch",
            name: "CASIO Edifice Men Digital Watch",
            price: "₹440.00",
            oldPrice: "₹550",
            brand: "Amazon.in",
            seller: "Amazon.in",
            rating: "4.1",
            reviews: "(39)",
            shipping: "Free delivery",
            discount: "LOW PRICE",
            accent: "from-[#eff1f4] to-[#d7dbe2]",
            art: "MV",
            image: "/watch-images/movado-bold-evolution.svg",
            id: ""
        },
        {
            kind: "watch",
            name: "Noise Twist 2 Smartwatch",
            price: "₹156.00",
            oldPrice: "₹195",
            brand: "Noise",
            seller: "Noise",
            rating: "4.2",
            reviews: "(14)",
            shipping: "Free delivery",
            discount: "LOW PRICE",
            accent: "from-[#f5efe4] to-[#dcc69f]",
            art: "F2",
            image: "/watch-images/shopping.webp",
            id: ""
        },
    ],
    Electronics: [
        {
            name: "Amazon Echo Show 5 Smart Display",
            price: "₹69.99",
            oldPrice: "₹90",
            brand: "Home Depot & more",
            seller: "Home Depot & more",
            rating: "4.6",
            reviews: "(5.6K)",
            shipping: "Free next-day delivery",
            discount: "22% OFF",
            accent: "from-[#eef0f2] to-[#d7dde5]",
            art: "ECHO5",
            kind: "electronics",
            id: ""
        },
        {
            name: "Amazon Echo Dot Smart Speaker with Alexa",
            price: "₹39.99",
            oldPrice: "₹50",
            brand: "Best Buy & more",
            seller: "Best Buy & more",
            rating: "4.7",
            reviews: "(20K)",
            shipping: "Free delivery by Sat",
            discount: "20% OFF",
            accent: "from-[#eff4fb] to-[#d5e0ef]",
            art: "DOT",
            kind: "electronics",
            id: ""
        },
        {
            name: "Google TV Streamer",
            price: "₹69.99",
            oldPrice: "₹100",
            brand: "Best Buy & more",
            seller: "Best Buy & more",
            rating: "4.3",
            reviews: "(11K)",
            shipping: "Pre-owned",
            discount: "30% OFF",
            accent: "from-[#f4f2ee] to-[#e6e0d6]",
            art: "TV",
            kind: "electronics",
            id: ""
        },
        {
            name: "Amazon Echo Show 11 Smart Display",
            price: "₹169.99",
            oldPrice: "₹220",
            brand: "Electronics & more",
            seller: "Electronics & more",
            rating: "4.6",
            reviews: "(351)",
            shipping: "Free delivery",
            discount: "22% OFF",
            accent: "from-[#eef0f3] to-[#dfe3ea]",
            art: "ECHO11",
            kind: "electronics",
            id: ""
        },
        {
            name: "Apple AirTag",
            price: "₹16.50",
            oldPrice: "₹29",
            brand: "Best Buy & more",
            seller: "Best Buy & more",
            rating: "4.8",
            reviews: "(65K)",
            shipping: "Free delivery",
            discount: "43% OFF",
            accent: "from-[#f5f5f5] to-[#e5e5e5]",
            art: "TAG",
            kind: "electronics",
            id: ""
        },
        {
            name: "JBL Charge 6 Portable Speaker",
            price: "₹161.34",
            oldPrice: "₹190",
            brand: "Excellent & more",
            seller: "Excellent & more",
            rating: "4.7",
            reviews: "(1.2K)",
            shipping: "Free delivery",
            discount: "15% OFF",
            accent: "from-[#f2f2f0] to-[#dbdbd8]",
            art: "JBL",
            kind: "electronics",
            id: ""
        },
        {
            name: "Roku Streaming Stick HD",
            price: "₹26.99",
            oldPrice: "₹30",
            brand: "Macy's & more",
            seller: "Macy's & more",
            rating: "4.8",
            reviews: "(9K)",
            shipping: "Free delivery",
            discount: "9% OFF",
            accent: "from-[#f0ebff] to-[#d8cbff]",
            art: "ROKU",
            kind: "electronics",
            id: ""
        },
        {
            name: "Microsoft Xbox Series X Console",
            price: "₹449.99",
            oldPrice: "₹480",
            brand: "Secret Cart",
            seller: "Secret Cart",
            rating: "4.7",
            reviews: "(1.8K)",
            shipping: "Free delivery",
            discount: "6% OFF",
            accent: "from-[#efefef] to-[#d8d8d8]",
            art: "XBOX",
            kind: "electronics",
            id: ""
        },
    ],
    "PS Stores": [
        {
            kind: "psstore",
            name: "Sony PlayStation Plus",
            price: "₹3,949",
            oldPrice: "₹4,499",
            brand: "PlayStation & more",
            seller: "PlayStation & more",
            rating: "4.9",
            reviews: "(8K)",
            shipping: "Free next-day delivery",
            discount: "ESSENTIAL",
            accent: "from-[#f2f2f0] to-[#e6e6e2]",
            art: "PS+1",
            id: ""
        },
        {
            kind: "psstore",
            name: "God Of War Digital...",
            price: "₹1,999",
            oldPrice: "₹2,499",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "5.0",
            reviews: "(10)",
            shipping: "Free next-day delivery",
            discount: "LOW PRICE",
            accent: "from-[#243746] to-[#0d1116]",
            art: "GOW",
            id: ""
        },
        {
            kind: "psstore",
            name: "Grand Theft Auto Online",
            price: "₹1,669",
            oldPrice: "₹1,999",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "4.7",
            reviews: "(50K)",
            shipping: "Free next-day delivery",
            discount: "LOW PRICE",
            accent: "from-[#2c1d2d] to-[#101014]",
            art: "GTA",
            id: ""
        },
        {
            kind: "psstore",
            name: "PlayStation Plus Extra...",
            price: "₹6,699",
            oldPrice: "₹7,299",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "5.0",
            reviews: "(1)",
            shipping: "Free next-day delivery",
            discount: "EXTRA",
            accent: "from-[#ffe24a] to-[#f0c200]",
            art: "PS+2",
            id: ""
        },
        {
            kind: "psstore",
            name: "Cricket 26 - The Offici...",
            price: "₹4,399",
            oldPrice: "₹4,999",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "4.0",
            reviews: "(11)",
            shipping: "Free next-day delivery",
            discount: "LOW PRICE",
            accent: "from-[#1f2430] to-[#08111a]",
            art: "CR26",
            id: ""
        },
    ],
    "PS Games": [
        {
            kind: "psstore",
            name: "Sony PlayStation Plus Essential",
            price: "₹3,949",
            oldPrice: "₹4,499",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "4.9",
            reviews: "(8K)",
            shipping: "Free next-day delivery",
            discount: "ESSENTIAL",
            accent: "from-[#0a2942] to-[#1a4a7a]",
            art: "PS+1",
            id: ""
        },
        {
            kind: "psstore",
            name: "God Of War Ragnarök",
            price: "₹2,499",
            oldPrice: "₹3,499",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "4.9",
            reviews: "(15K)",
            shipping: "Free delivery",
            discount: "29% OFF",
            accent: "from-[#243746] to-[#0d1116]",
            art: "GOW",
            id: ""
        },
        {
            kind: "psstore",
            name: "Marvel's Spider-Man 2",
            price: "₹3,999",
            oldPrice: "₹4,499",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "4.8",
            reviews: "(12K)",
            shipping: "Free delivery",
            discount: "11% OFF",
            accent: "from-[#1f2430] to-[#08111a]",
            art: "SPM",
            id: ""
        },
        {
            kind: "psstore",
            name: "PlayStation Plus Extra",
            price: "₹6,699",
            oldPrice: "₹7,299",
            brand: "PlayStation Store",
            seller: "PlayStation Store",
            rating: "5.0",
            reviews: "(1K)",
            shipping: "Free delivery",
            discount: "EXTRA",
            accent: "from-[#ffe24a] to-[#f0c200]",
            art: "PS+2",
            id: ""
        },
    ],
};
